---
title: "Untitled"
author: "Chenxi Liao"
date: "8/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(fmsb)
```

## Plot Radar chart for Material categorization task
```{r}
filename = "radar data.csv"
filename2 = "radar data color.csv"
filename3 = "radar data gray.csv"


plot_radar<-function(filename, title){
radar_data <- read.csv(filename) %>%
  drop_na()

radar_data

radar_data <- rbind(rep(15,300) , rep(0,300) , radar_data)
colors_border2= c("red", rgb(0.3,0.4,0.8,0.7))
colors_in2= "blue"

# plot with default options:
radarchart( radar_data  , axistype=0 , 
    #custom polygon
    pcol=colors_border2, plwd=0.5 , plty=1,
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,15,4), cglwd=0.5,
    #custom labels
    vlcex=0.2, title = title
    )
}
```


```{r}
crsytal = "crystal.csv"
plot_radar(crsytal, "crystal")
```

```{r}
food = "food.csv"
plot_radar(food, "food")
```

```{r}
glass = "glass.csv"
plot_radar(glass, "glass")
```

```{r}
marble = "marble.csv"
plot_radar(marble, "marble")
```

```{r}
metal = "metal.csv"
plot_radar(metal, "metal")
```

```{r}
plastic = "plastic.csv"
plot_radar(plastic, "plastic")
```

```{r}
wax = "wax.csv"
plot_radar(wax, "wax")
```

```{r}
soap = "soap.csv"
plot_radar(soap, "soap")
```