---
title: "linear-reg"
author: "Chenxi Liao"
date: "7/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
```


```{r}

plot_kendall <- function(filename, col, outcome){ data <- read.csv(filename)
  data <- data %>%
    arrange(total.vote)
  
  print(data)
  
  base_scatter <- ggscatter(data, x = "total.vote", y = outcome, 
          xlab = FALSE,
          ylab = FALSE,
          #cor.coef = TRUE,
          cor.coeff.args = list(method = "kendall", label.y.npc = "top")) + 
          geom_point(colour = col, size = 3) +
          ylim(1, 6)
  scatter <- base_scatter + stat_cor(method = "kendall",
          label.x = 5, label.y = 6,
          cor.coef.name = "tau",
          size = 10,
          digit = 2,
          p.accuracy = 0.05)
          #cor.coef = TRUE,
          #cor.coeff.args = list(method = "kendall", label.y.npc = "top"))
                  
  
  print(scatter + theme(
  axis.title.x=element_blank(),
  axis.text.x=element_blank(),
  axis.ticks.x=element_blank(),
  axis.title.y=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks.y=element_blank(),
  ))
}


```

```{r}
for (avg_attribute in  c("average_see_through", "average_gloss", "average_softness", "average_glow", "average_density")){
  plot_kendall("../exp data/color_BC_SAR/color_labeled.csv", col = "red3", outcome = avg_attribute)
}

```


```{r}
for (avg_attribute in  c("average_see_through", "average_gloss", "average_softness", "average_glow", "average_density")){
  plot_kendall("../exp data/gray_BC_SAR/gray_labeled.csv", col = "blue2", outcome = avg_attribute)
}

```

